# Generated by Django 4.2.6 on 2023-10-30 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Eleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('sexe', models.CharField(choices=[('Masculin', 'masculin'), ('Feminin', 'feminin')], max_length=30)),
                ('date_nais', models.DateField(default=None)),
                ('adresse', models.CharField(default=None, max_length=30)),
                ('telephone', models.CharField(default=None, max_length=30)),
                ('classe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='Gestion.classe')),
            ],
        ),
    ]
