# Generated by Django 4.2.6 on 2023-10-31 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_eleves_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranchePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_tranche', models.IntegerField()),
                ('date_limite', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='eleves',
            name='adresse',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='date_nais',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='nom',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='prenom',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Masculin', 'masculin'), ('Feminin', 'feminin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='statut',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eleves',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date_paiement', models.DateField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.eleves')),
            ],
        ),
    ]
