# Generated by Django 4.2.6 on 2023-10-31 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_tranchepaiement_alter_eleves_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranchepaiement',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='Gestion.classe'),
        ),
        migrations.AddField(
            model_name='tranchepaiement',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
