# Generated by Django 4.2.6 on 2023-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_alter_eleves_date_nais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleves',
            options={'ordering': ['nom']},
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
